### PR TITLE
chore: update api short name

### LINKED ISSUE #449: Your .repo-metadata.json file has a problem 🤒
You have a problem with your .repo-metadata.json file:

Result of scan 📈:

* api_shortname 'grafeas' invalid in .repo-metadata.json

 ☝️ Once you address these problems, you can close this issue.

### Need help?
* [Schema definition](https://github.com/googleapis/repo-automation-bots/blob/main/packages/repo-metadata-lint/src/repo-metadata-schema.json): lists valid options for each field.
* [API index](https://github.com/googleapis/googleapis/blob/master/api-index-v1.json): for gRPC libraries **api_shortname** should match the subdomain of an API's **hostName**.
* Reach out to **go/github-automation** if you have any questions.

### PR DESCRIPTION
**Pull request by averikitsch**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-grafeas/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #449

### CODE REVIEW

**Review by ace-n — APPROVED** [review]
LGTM. I'll ask Yoshi folks to review as well.

**Comment by eaball35** [comment]
This stuff should be templated (example: https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/java_library/.kokoro/common.cfg) and will get updated if you update the [.repo-metadata](https://github.com/googleapis/java-grafeas/blob/main/.repo-metadata.json) instead

**Review by eaball35 — CHANGES_REQUESTED** [review]
Update in .repo-metadata instead

**Comment by averikitsch** [comment]
I edited the wrong field. I will send in a new PR

**Pull request closed without merging**
